/*
 * emuera —— Emuera（ERB 脚本引擎）的 Qt6 + QML/C++ 移植
 * Copyright (C) 2026  yigekuyou
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
// ---------------------------------------------------------------------------
// test_ecd_command_coverage.cpp —— ecd/docs 命令表覆盖（识别层）
//
// 命令名取自仓库内 ecd/docs（reference/ERB_Commands.html、
// translation/Command.html、ERB_Statements.html）。本测试断言引擎的
// **解析层**认识这些名字（AstBuilder::isKnownInstructionName）——
// 不认识 = 脚本里会被当成「未识别指令 / 未定义函数」静默跳过。
//
// 文档里混入的关键字/变量名/实参说明（如 IF/ELSE/ENDIF/WEND/DAY/FLAG/XXX）
// 不是指令，列入下面的 kNotCommands 白名单。
// ---------------------------------------------------------------------------
#include <QCoreApplication>
#include <QDebug>
#include <QSet>
#include <QString>
#include <QStringList>

#include "ast/ast_builder.h"
#include "ast/function_types.h"

static int g_failures = 0;

int main(int argc, char* argv[]) {
    QCoreApplication app(argc, argv);
    qDebug() << "ecd/docs 命令表覆盖（识别层）";
    qDebug() << "==================================";

    const QStringList kDocNames = {
    QStringLiteral("ABS"),
    QStringLiteral("ADDCHARA"),
    QStringLiteral("ADDCOPYCHARA"),
    QStringLiteral("ADDDEFCHARA"),
    QStringLiteral("ADDSPCHARA"),
    QStringLiteral("ADDVOIDCHARA"),
    QStringLiteral("ALIGNMENT"),
    QStringLiteral("ARRAYCOPY"),
    QStringLiteral("ARRAYREMOVE"),
    QStringLiteral("ARRAYSHIFT"),
    QStringLiteral("ARRAYSORT"),
    QStringLiteral("ASSERT"),
    QStringLiteral("ASSI"),
    QStringLiteral("AWAIT"),
    QStringLiteral("BACK"),
    QStringLiteral("BAR"),
    QStringLiteral("BARSTR"),
    QStringLiteral("BEGIN"),
    QStringLiteral("BOLD"),
    QStringLiteral("BREAK"),
    QStringLiteral("CALL"),
    QStringLiteral("CALLF"),
    QStringLiteral("CALLFORM"),
    QStringLiteral("CALLFORMF"),
    QStringLiteral("CALLNAME"),
    QStringLiteral("CALLTRAIN"),
    QStringLiteral("CASE"),
    QStringLiteral("CASEELSE"),
    QStringLiteral("CATCH"),
    QStringLiteral("CBG"),
    QStringLiteral("CBGCLEAR"),
    QStringLiteral("CBGCLEARBUTTON"),
    QStringLiteral("CBGREMOVEBMAP"),
    QStringLiteral("CBGREMOVERANGE"),
    QStringLiteral("CBGSETBMAPG"),
    QStringLiteral("CBGSETBUTTONSPRITE"),
    QStringLiteral("CBGSETG"),
    QStringLiteral("CBGSETSPRITE"),
    QStringLiteral("CDOWN"),
    QStringLiteral("CENTER"),
    QStringLiteral("CFLAG"),
    QStringLiteral("CHARANUM"),
    QStringLiteral("CHARATU"),
    QStringLiteral("CHKDATA"),
    QStringLiteral("CHKFONT"),
    QStringLiteral("CLEARBIT"),
    QStringLiteral("CLEARLINE"),
    QStringLiteral("CLEARTEXTBOX"),
    QStringLiteral("CLIENTHEIGHT"),
    QStringLiteral("CLIENTWIDTH"),
    QStringLiteral("COLOR"),
    QStringLiteral("COLOR_FROMNAME"),
    QStringLiteral("COLOR_FROMRGB"),
    QStringLiteral("COM_ABLE"),
    QStringLiteral("CONTINUE"),
    QStringLiteral("COPYCHARA"),
    QStringLiteral("COUNT"),
    QStringLiteral("CSTR"),
    QStringLiteral("CSVABL"),
    QStringLiteral("CSVBASE"),
    QStringLiteral("CSVCALLNAME"),
    QStringLiteral("CSVCFLAG"),
    QStringLiteral("CSVCSTR"),
    QStringLiteral("CSVEQUIP"),
    QStringLiteral("CSVEXP"),
    QStringLiteral("CSVJULE"),
    QStringLiteral("CSVMARK"),
    QStringLiteral("CSVMASTERNAME"),
    QStringLiteral("CSVNAME"),
    QStringLiteral("CSVNICKNAME"),
    QStringLiteral("CSVRELATION"),
    QStringLiteral("CSVTALENT"),
    QStringLiteral("CUP"),
    QStringLiteral("CUPCHECK"),
    QStringLiteral("CURRENTALIGN"),
    QStringLiteral("CURRENTREDRAW"),
    QStringLiteral("CUSTOMDRAWLINE"),
    QStringLiteral("CVARSET"),
    QStringLiteral("DATA"),
    QStringLiteral("DATALIST"),
    QStringLiteral("DAY"),
    QStringLiteral("DEBUG"),
    QStringLiteral("DEBUGPRINT"),
    QStringLiteral("DEBUGPRINTFORM"),
    QStringLiteral("DEBUGPRINTFORML"),
    QStringLiteral("DEBUGPRINTL"),
    QStringLiteral("DELALLCHARA"),
    QStringLiteral("DELCHARA"),
    QStringLiteral("DELDATA"),
    QStringLiteral("DIM"),
    QStringLiteral("DIMS"),
    QStringLiteral("DITEMTYPE"),
    QStringLiteral("DO"),
    QStringLiteral("DOTRAIN"),
    QStringLiteral("DOWN"),
    QStringLiteral("DRAWLINE"),
    QStringLiteral("DRAWLINEFORM"),
    QStringLiteral("DUMPRAND"),
    QStringLiteral("ELSE"),
    QStringLiteral("ELSEIF"),
    QStringLiteral("ENCODETOUNI"),
    QStringLiteral("ENDCATCH"),
    QStringLiteral("ENDDATA"),
    QStringLiteral("ENDFUNC"),
    QStringLiteral("ENDIF"),
    QStringLiteral("ENDLIST"),
    QStringLiteral("ENDNOSKIP"),
    QStringLiteral("ENDSELECT"),
    QStringLiteral("ERH"),
    QStringLiteral("ESCAPE"),
    QStringLiteral("EXISTCSV"),
    QStringLiteral("EXPLV"),
    QStringLiteral("FINDCHARA"),
    QStringLiteral("FINDELEMENT"),
    QStringLiteral("FINDLASTCHARA"),
    QStringLiteral("FINDLASTELEMENT"),
    QStringLiteral("FIRST"),
    QStringLiteral("FLAG"),
    QStringLiteral("FONTBOLD"),
    QStringLiteral("FONTITALIC"),
    QStringLiteral("FONTREGULAR"),
    QStringLiteral("FONTSTYLE"),
    QStringLiteral("FOR"),
    QStringLiteral("FORCEKANA"),
    QStringLiteral("FORCEWAIT"),
    QStringLiteral("FORM"),
    QStringLiteral("FORMS"),
    QStringLiteral("FORWARD"),
    QStringLiteral("FUNC"),
    QStringLiteral("GCLEAR"),
    QStringLiteral("GCREATE"),
    QStringLiteral("GCREATED"),
    QStringLiteral("GCREATEFROMFILE"),
    QStringLiteral("GDISPOSE"),
    QStringLiteral("GDRAWG"),
    QStringLiteral("GDRAWGWITHMASK"),
    QStringLiteral("GDRAWSPRITE"),
    QStringLiteral("GETBGCOLOR"),
    QStringLiteral("GETBIT"),
    QStringLiteral("GETCHARA"),
    QStringLiteral("GETCOLOR"),
    QStringLiteral("GETDEFBGCOLOR"),
    QStringLiteral("GETDEFCOLOR"),
    QStringLiteral("GETEXPLV"),
    QStringLiteral("GETFOCUSCOLOR"),
    QStringLiteral("GETFONT"),
    QStringLiteral("GETKEY"),
    QStringLiteral("GETKEYTRIGGERED"),
    QStringLiteral("GETMILLISECOND"),
    QStringLiteral("GETNUM"),
    QStringLiteral("GETPALAMLV"),
    QStringLiteral("GETSECOND"),
    QStringLiteral("GETSPCHARA"),
    QStringLiteral("GETSTYLE"),
    QStringLiteral("GETTIME"),
    QStringLiteral("GFILLRECTANGLE"),
    QStringLiteral("GGETCOLOR"),
    QStringLiteral("GHEIGHT"),
    QStringLiteral("GLOAD"),
    QStringLiteral("GLOBAL"),
    QStringLiteral("GLOBALS"),
    QStringLiteral("GOTO"),
    QStringLiteral("GOTOFORM"),
    QStringLiteral("GRAPHICS"),
    QStringLiteral("GSAVE"),
    QStringLiteral("GSETBRUSH"),
    QStringLiteral("GSETCOLOR"),
    QStringLiteral("GSETFONT"),
    QStringLiteral("GSETPEN"),
    QStringLiteral("GWIDTH"),
    QStringLiteral("HTML"),
    QStringLiteral("HTML_PRINT"),
    QStringLiteral("HTML_TAGSPLIT"),
    QStringLiteral("ID"),
    QStringLiteral("IF"),
    QStringLiteral("INITRAND"),
    QStringLiteral("INPUT"),
    QStringLiteral("INPUTMOUSEKEY"),
    QStringLiteral("INPUTS"),
    QStringLiteral("INRANGE"),
    QStringLiteral("INVERTBIT"),
    QStringLiteral("IS"),
    QStringLiteral("ISACTIVE"),
    QStringLiteral("ISASSI"),
    QStringLiteral("ISNUMERIC"),
    QStringLiteral("ISSKIP"),
    QStringLiteral("ITALIC"),
    QStringLiteral("JUMP"),
    QStringLiteral("JUMPFORM"),
    QStringLiteral("KOJO_"),
    QStringLiteral("LC"),
    QStringLiteral("LCNT"),
    QStringLiteral("LEFT"),
    QStringLiteral("LIMIT"),
    QStringLiteral("LINECOUNT"),
    QStringLiteral("LINEISEMPTY"),
    QStringLiteral("LOADDATA"),
    QStringLiteral("LOADGAME"),
    QStringLiteral("LOADGLOBAL"),
    QStringLiteral("LOCALS"),
    QStringLiteral("LOOP"),
    QStringLiteral("MASTER"),
    QStringLiteral("MASTERNAME"),
    QStringLiteral("MAX"),
    QStringLiteral("MIN"),
    QStringLiteral("MONEYSTR"),
    QStringLiteral("MOUSESKIP"),
    QStringLiteral("MOUSEX"),
    QStringLiteral("MOUSEY"),
    QStringLiteral("NAME"),
    QStringLiteral("NEXT"),
    QStringLiteral("NICKNAME"),
    QStringLiteral("NO"),
    QStringLiteral("NOSKIP"),
    QStringLiteral("ONEINPUT"),
    QStringLiteral("ONEINPUTS"),
    QStringLiteral("OUTPUTLOG"),
    QStringLiteral("PALAMLV"),
    QStringLiteral("PICKUPCHARA"),
    QStringLiteral("POWER"),
    QStringLiteral("PRINT"),
    QStringLiteral("PRINTBUTTON"),
    QStringLiteral("PRINTC"),
    QStringLiteral("PRINTCPERLINE"),
    QStringLiteral("PRINTDATA"),
    QStringLiteral("PRINTFORM"),
    QStringLiteral("PRINTFORML"),
    QStringLiteral("PRINTFORMW"),
    QStringLiteral("PRINTL"),
    QStringLiteral("PRINTPLAIN"),
    QStringLiteral("PRINTS"),
    QStringLiteral("PRINTSDW"),
    QStringLiteral("PRINTSINGLE"),
    QStringLiteral("PRINTSL"),
    QStringLiteral("PRINTV"),
    QStringLiteral("PRINT_IMG"),
    QStringLiteral("PRINT_RECT"),
    QStringLiteral("PRINT_SPACE"),
    QStringLiteral("PUTFORM"),
    QStringLiteral("QUIT"),
    QStringLiteral("RAND"),
    QStringLiteral("RANDDATA"),
    QStringLiteral("RANDOMIZE"),
    QStringLiteral("REDRAW"),
    QStringLiteral("REGULAR"),
    QStringLiteral("REND"),
    QStringLiteral("REPEAT"),
    QStringLiteral("REPLACE"),
    QStringLiteral("RESETBGCOLOR"),
    QStringLiteral("RESETCOLOR"),
    QStringLiteral("RESETDATA"),
    QStringLiteral("RESETGLOBAL"),
    QStringLiteral("RESET_STAIN"),
    QStringLiteral("RESULT"),
    QStringLiteral("RESULTS"),
    QStringLiteral("RETURN"),
    QStringLiteral("RETURNF"),
    QStringLiteral("RETURNFORM"),
    QStringLiteral("REUSELASTLINE"),
    QStringLiteral("RIGHT"),
    QStringLiteral("SAVEDATA"),
    QStringLiteral("SAVEGAME"),
    QStringLiteral("SAVEGLOBAL"),
    QStringLiteral("SAVENOS"),
    QStringLiteral("SELECTCASE"),
    QStringLiteral("SELECTCOM"),
    QStringLiteral("SETANIMETIMER"),
    QStringLiteral("SETBGCOLOR"),
    QStringLiteral("SETBGCOLORBYNAME"),
    QStringLiteral("SETBIT"),
    QStringLiteral("SETCOLOR"),
    QStringLiteral("SETCOLORBYNAME"),
    QStringLiteral("SETFONT"),
    QStringLiteral("SETSTYLE"),
    QStringLiteral("SHOW_STATUS"),
    QStringLiteral("SHOW_USERCOM"),
    QStringLiteral("SIF"),
    QStringLiteral("SIGN"),
    QStringLiteral("SKIPDISP"),
    QStringLiteral("SORTCHARA"),
    QStringLiteral("SPLIT"),
    QStringLiteral("SPRITE"),
    QStringLiteral("SPRITEANIMEADDFRAME"),
    QStringLiteral("SPRITEANIMECREATE"),
    QStringLiteral("SPRITECREATE"),
    QStringLiteral("SPRITECREATED"),
    QStringLiteral("SPRITEDISPOSE"),
    QStringLiteral("SPRITEGETCOLOR"),
    QStringLiteral("SPRITEHEIGHT"),
    QStringLiteral("SPRITEMOVE"),
    QStringLiteral("SPRITEPOSX"),
    QStringLiteral("SPRITEPOSY"),
    QStringLiteral("SPRITESETPOS"),
    QStringLiteral("SPRITEWIDTH"),
    QStringLiteral("SQRT"),
    QStringLiteral("STAIN"),
    QStringLiteral("STOPCALLTRAIN"),
    QStringLiteral("STR"),
    QStringLiteral("STRCOUNT"),
    QStringLiteral("STRDATA"),
    QStringLiteral("STRFIND"),
    QStringLiteral("STRFINDU"),
    QStringLiteral("STRLEN"),
    QStringLiteral("STRLENFORM"),
    QStringLiteral("STRLENFORMU"),
    QStringLiteral("STRLENS"),
    QStringLiteral("STRLENSU"),
    QStringLiteral("STRLENU"),
    QStringLiteral("SUBSTRING"),
    QStringLiteral("SUBSTRINGU"),
    QStringLiteral("SWAP"),
    QStringLiteral("SWAPCHARA"),
    QStringLiteral("TA"),
    QStringLiteral("TARGET"),
    QStringLiteral("TEST"),
    QStringLiteral("TEXTRENDERER"),
    QStringLiteral("THROW"),
    QStringLiteral("TINPUT"),
    QStringLiteral("TINPUTS"),
    QStringLiteral("TITLE"),
    QStringLiteral("TO"),
    QStringLiteral("TOFULL"),
    QStringLiteral("TOHALF"),
    QStringLiteral("TOINT"),
    QStringLiteral("TOLOWER"),
    QStringLiteral("TONEINPUT"),
    QStringLiteral("TONEINPUTS"),
    QStringLiteral("TOOLTIP_SETCOLOR"),
    QStringLiteral("TOOLTIP_SETDELAY"),
    QStringLiteral("TOOLTIP_SETDURATION"),
    QStringLiteral("TOSTR"),
    QStringLiteral("TOUPPER"),
    QStringLiteral("TRAIN"),
    QStringLiteral("TRAINNAME"),
    QStringLiteral("TRYC"),
    QStringLiteral("TRYCALL"),
    QStringLiteral("TRYCALLFORM"),
    QStringLiteral("TRYCALLLIST"),
    QStringLiteral("TRYCCALL"),
    QStringLiteral("TRYCCALLFORM"),
    QStringLiteral("TRYCGOTO"),
    QStringLiteral("TRYCGOTOFORM"),
    QStringLiteral("TRYCJUMP"),
    QStringLiteral("TRYCJUMPFORM"),
    QStringLiteral("TRYGOTO"),
    QStringLiteral("TRYGOTOFORM"),
    QStringLiteral("TRYGOTOLIST"),
    QStringLiteral("TRYJUMP"),
    QStringLiteral("TRYJUMPFORM"),
    QStringLiteral("TRYJUMPLIST"),
    QStringLiteral("TRYLIST"),
    QStringLiteral("TWAIT"),
    QStringLiteral("UNICODE"),
    QStringLiteral("UNKNOWN_FUNC"),
    QStringLiteral("UP"),
    QStringLiteral("UPCHECK"),
    QStringLiteral("VARSET"),
    QStringLiteral("VARSIZE"),
    QStringLiteral("WAIT"),
    QStringLiteral("WAITANYKEY"),
    QStringLiteral("WEND"),
    QStringLiteral("WHILE"),
    QStringLiteral("WINAPI"),
    QStringLiteral("XXX"),
    QStringLiteral("YYY"),
    QStringLiteral("ZZZ")
    };

    // 文档中出现的「非指令」记号：控制流关键字 / 变量名 / 实参占位 / 示例噪声
    static const QSet<QString> kNotCommands = {
        // 控制流关键字（由解析层结构处理，不走指令表）
        QStringLiteral("IF"), QStringLiteral("ELSE"), QStringLiteral("ELSEIF"),
        QStringLiteral("ENDIF"), QStringLiteral("WHILE"), QStringLiteral("WEND"),
        QStringLiteral("FOR"), QStringLiteral("NEXT"), QStringLiteral("REPEAT"),
        QStringLiteral("LOOP"), QStringLiteral("BREAK"), QStringLiteral("CONTINUE"),
        QStringLiteral("SELECTCASE"), QStringLiteral("CASE"), QStringLiteral("CASEELSE"),
        QStringLiteral("ENDSELECT"), QStringLiteral("CATCH"), QStringLiteral("ENDCATCH"),
        QStringLiteral("DO"), QStringLiteral("TO"), QStringLiteral("IS"),
        QStringLiteral("DIM"), QStringLiteral("DIMS"), QStringLiteral("ERH"),
        QStringLiteral("FUNC"), QStringLiteral("ENDFUNC"), QStringLiteral("DITEMTYPE"),
        // 变量名（非指令）
        QStringLiteral("DAY"), QStringLiteral("MONEY"), QStringLiteral("FLAG"),
        QStringLiteral("TFLAG"), QStringLiteral("CFLAG"), QStringLiteral("CSTR"),
        QStringLiteral("UP"), QStringLiteral("DOWN"), QStringLiteral("CUP"),
        QStringLiteral("CDOWN"), QStringLiteral("EXPLV"), QStringLiteral("PALAMLV"),
        QStringLiteral("STAIN"), QStringLiteral("TARGET"), QStringLiteral("ASSI"),
        QStringLiteral("MASTER"), QStringLiteral("NO"), QStringLiteral("NAME"),
        QStringLiteral("CALLNAME"), QStringLiteral("NICKNAME"), QStringLiteral("MASTERNAME"),
        QStringLiteral("CSVNAME"), QStringLiteral("CSVCALLNAME"), QStringLiteral("CSVNICKNAME"),
        QStringLiteral("CSVMASTERNAME"), QStringLiteral("CSVABL"), QStringLiteral("CSVBASE"),
        QStringLiteral("CSVCFLAG"), QStringLiteral("CSVCSTR"), QStringLiteral("CSVEQUIP"),
        QStringLiteral("CSVEXP"), QStringLiteral("CSVJULE"), QStringLiteral("CSVMARK"),
        QStringLiteral("CSVRELATION"), QStringLiteral("CSVTALENT"), QStringLiteral("GLOBAL"),
        QStringLiteral("GLOBALS"), QStringLiteral("LOCALS"), QStringLiteral("RESULT"),
        QStringLiteral("RESULTS"), QStringLiteral("RANDDATA"), QStringLiteral("SELECTCOM"),
        QStringLiteral("TRAINNAME"), QStringLiteral("CHARANUM"), QStringLiteral("LINECOUNT"),
        QStringLiteral("MONEYSTR"), QStringLiteral("BARSTR"), QStringLiteral("STR"),
        QStringLiteral("FIRST"), QStringLiteral("NEXT"), QStringLiteral("TEST"),
        QStringLiteral("XXX"), QStringLiteral("YYY"), QStringLiteral("ZZZ"),
        QStringLiteral("UNKNOWN_FUNC"), QStringLiteral("WINAPI"), QStringLiteral("REND"),
        QStringLiteral("LCNT"), QStringLiteral("KOJO_"), QStringLiteral("ID"),
        QStringLiteral("COM_ABLE"), QStringLiteral("SHOW_STATUS"), QStringLiteral("SHOW_USERCOM"),
        QStringLiteral("TRAIN"), QStringLiteral("GRAPHICS"), QStringLiteral("HTML"),
        QStringLiteral("CBG"), QStringLiteral("SPRITE"),
        // 排序方向 / 配置值 / 调试模式 / 变量 —— 都不是指令
        QStringLiteral("BACK"), QStringLiteral("FORWARD"), QStringLiteral("DEBUG"),
        QStringLiteral("TEXTRENDERER"), QStringLiteral("TA"), QStringLiteral("COUNT"),
        QStringLiteral("ISASSI"),
    };

    // 实参/对齐/字体样式等「值记号」（出现在命令实参里，不是指令）
    static const QSet<QString> kValueTokens = {
        QStringLiteral("LEFT"), QStringLiteral("CENTER"), QStringLiteral("RIGHT"),
        QStringLiteral("BOLD"), QStringLiteral("ITALIC"), QStringLiteral("REGULAR"),
        QStringLiteral("RGB"), QStringLiteral("FORM"), QStringLiteral("FORMS"),
        QStringLiteral("LC"), QStringLiteral("CLIENTWIDTH"), QStringLiteral("CLIENTHEIGHT"),
        QStringLiteral("COLOR"), QStringLiteral("COLOR_FROMNAME"), QStringLiteral("COLOR_FROMRGB"),
        QStringLiteral("TITLE"), QStringLiteral("SPRITE"),
    };

    QStringList unknown;
    for (const QString& n : kDocNames) {
        if (kNotCommands.contains(n) || kValueTokens.contains(n)) continue;
        if (!AstBuilder::isKnownInstructionName(n) && !isBuiltinFunction(n.toStdString()))
            unknown.append(n);
    }
    qDebug().noquote() << "\n文档命令总数" << kDocNames.size()
                       << "，其中未识别" << unknown.size();
    if (!unknown.isEmpty()) {
        qDebug().noquote() << "未识别（需补指令表/白名单）:";
        for (const QString& n : unknown) {
            qDebug().noquote() << "  [MISS]" << n;
            ++g_failures;
        }
    }

    qDebug() << "\n==============================";
    if (g_failures == 0) {
        qDebug() << "[SUCCESS] ecd 命令表全部被解析层认识";
        return 0;
    }
    qDebug() << "[FAILURE]" << g_failures << "个命令未被识别";
    return 1;
}
