#include "game_library.h"
#include "GameData/game_paths.h"
#include "GameData/file_system_io.h"
#include "GameView/audio_pipeline_pool.h"
#include "GameView/resource_image_provider.h"
#include <QGuiApplication>
#include <QQmlEngine>
#include <QQmlComponent>
#include <QImage>
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QSettings>
#include <QTemporaryDir>
#include <QStandardPaths>
#include <QtTest>

class GameLibraryTest : public QObject {
    Q_OBJECT
private slots:
    void pathsAndLocalStorage() {
        const QString uri = "content://provider/tree/primary%3Aera%20games/document/opaque%3A42";
        QCOMPARE(GamePaths::normalize(uri), uri);
        FileSystem fs;
        fs.setRootDir(uri);
        QCOMPARE(fs.normalizePath(uri), uri);
        QVERIFY(fs.getDirectoryPath(uri).isEmpty());
        QVERIFY(GamePaths::join(uri, "../outside").isEmpty());
        QTemporaryDir temp;
        QVERIFY(temp.isValid());
        QCOMPARE(GamePaths::normalize(QUrl::fromLocalFile(temp.path()).toString()), temp.path());
        QCOMPARE(GamePaths::storageRoot(temp.path()), temp.path());
        const QString local = GamePaths::storageRoot(uri);
        QVERIFY(!GamePaths::isContent(local));
        QVERIFY(QFileInfo(local + "/sav").isDir());
        QCOMPARE(GamePaths::storageRoot(uri), local);
        QVERIFY(GamePaths::storageRoot(uri + "-other") != local);
        QVERIFY(QDir(local).entryList(QDir::Files).isEmpty());
    }
    void resourcesRemainInGame() {
        QTemporaryDir temp;
        QDir root(temp.path());
        QVERIFY(root.mkpath("resources/nested"));
        QVERIFY(root.mkpath("sound"));
        QImage image(7, 9, QImage::Format_RGB32);
        image.fill(Qt::red);
        QVERIFY(image.save(root.filePath("resources/nested/picture.png")));
        QFile atlas(root.filePath("resources/nested/atlas.csv"));
        QVERIFY(atlas.open(QIODevice::WriteOnly));
        atlas.write("sprite,picture.png\n");
        atlas.close();
        ResourceImageProvider::setRoot(temp.path());
        QVERIFY(ResourceImageProvider::hasResource("sprite"));
        QFile audio(root.filePath("sound/music.ogg"));
        QVERIFY(audio.open(QIODevice::WriteOnly));
        audio.write("test");
        audio.close();
        AudioPipelinePool pool;
        pool.setSoundDirectory(temp.path());
        QCOMPARE(pool.resolveSource("music"), root.filePath("sound/music.ogg"));
    }
    void qmlElementMetadata() {
        QQmlEngine engine;
        // Test instance registration independently; app module registration is
        // generated by qt_add_qml_module and checked by qmllint/build.
        qmlRegisterType<GameLibrary>("Emuera.Library.Test", 1, 0, "GameLibrary");
        QQmlComponent component(&engine);
        component.setData("import Emuera.Library.Test 1.0; GameLibrary {}", QUrl());
        QScopedPointer<QObject> instance(component.create());
        QVERIFY2(instance, qPrintable(component.errorString()));
        QVERIFY(instance->metaObject()->indexOfProperty("scanRoot") >= 0);
    }
    void libraryIsBoundedAndPersistent() {
        QTemporaryDir temp;
        QVERIFY(temp.isValid());
        QCoreApplication::setOrganizationName("emuera-tests");
        QCoreApplication::setApplicationName("game-library");
        QSettings::setDefaultFormat(QSettings::IniFormat);
        QSettings::setPath(QSettings::IniFormat, QSettings::UserScope, temp.path());
        QSettings(QStringLiteral("yigekuyou"), QStringLiteral("eraemu")).clear();
        QDir root(temp.path());
        QVERIFY(root.mkpath("library/valid/csv"));
        QVERIFY(root.mkpath("library/valid/ErB"));
        QVERIFY(root.mkpath("library/incomplete/CSV"));
        QVERIFY(root.mkpath("outside/CSV"));
        QVERIFY(root.mkpath("outside/ERB"));
        GameLibrary library;
        library.setScanRoot(QUrl::fromLocalFile(root.filePath("library")).toString());
        QCOMPARE(library.games().size(), 1);
        QCOMPARE(library.games().first().toMap().value("name").toString(), QString("valid"));
        const QString valid = root.filePath("library/valid");
        QCOMPARE(library.prepareGame(valid), valid);
        QVERIFY(library.prepareGame(root.filePath("outside")).isEmpty());
        QVERIFY(!library.error().isEmpty());
        GameLibrary restored;
        QCOMPARE(restored.scanRoot(), library.scanRoot());
        QCOMPARE(restored.games().size(), 1);
        const QString oldRoot = library.scanRoot();
        library.setScanRoot(root.filePath("missing"));
        QCOMPARE(library.scanRoot(), oldRoot);
        QVERIFY(!library.error().isEmpty());
        QSignalSpy ready(&restored, &GameLibrary::gameReady);
        restored.selectGame(valid);
        QTRY_COMPARE(ready.size(), 1);
        QCOMPARE(ready.first().first().toString(), valid);
        QVERIFY(!restored.busy());
        QVERIFY(QDir(valid).removeRecursively());
        restored.refresh();
        QVERIFY(restored.games().isEmpty());
    }
};
int main(int argc, char** argv) {
    QGuiApplication app(argc, argv);
    QStandardPaths::setTestModeEnabled(true);
    GameLibraryTest test;
    return QTest::qExec(&test, argc, argv);
}
#include "test_game_library.moc"
